//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRISDBEntities : DbContext
    {
        public HRISDBEntities()
            : base("name=HRISDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tOrgCluster> tOrgClusters { get; set; }
        public DbSet<tOrgDepartment> tOrgDepartments { get; set; }
        public DbSet<tOrgDivision> tOrgDivisions { get; set; }
        public DbSet<tOrgSection> tOrgSections { get; set; }
        public DbSet<tOrgStructure> tOrgStructures { get; set; }
        public DbSet<tOrgUnit> tOrgUnits { get; set; }
        public DbSet<tRSPEmployee> tRSPEmployees { get; set; }
        public DbSet<tRSPEmploymentStatu> tRSPEmploymentStatus { get; set; }
        public DbSet<tRSPlantillaMagnaCarta> tRSPlantillaMagnaCartas { get; set; }
        public DbSet<tRSPMagnaCarta> tRSPMagnaCartas { get; set; }
        public DbSet<tRSPPlantilla> tRSPPlantillas { get; set; }
        public DbSet<tRSPPlantillaPersonnel> tRSPPlantillaPersonnels { get; set; }
        public DbSet<tRSPPosition> tRSPPositions { get; set; }
        public DbSet<tRSPSalaryTable> tRSPSalaryTables { get; set; }
        public DbSet<tRSPSalaryTableDetail> tRSPSalaryTableDetails { get; set; }
        public DbSet<tRSPServiceRecord> tRSPServiceRecords { get; set; }
        public DbSet<tRSPServiceRecordRemark> tRSPServiceRecordRemarks { get; set; }
    }
}
