//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrgCluster
    {
        public tOrgCluster()
        {
            this.tOrgStructures = new HashSet<tOrgStructure>();
        }
    
        public int recNo { get; set; }
        public string clusterCode { get; set; }
        public string clusterName { get; set; }
    
        public virtual ICollection<tOrgStructure> tOrgStructures { get; set; }
    }
}
