//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrgStructure
    {
        public tOrgStructure()
        {
            this.tRSPPlantillas = new HashSet<tRSPPlantilla>();
        }
    
        public int recNo { get; set; }
        public string structureCode { get; set; }
        public string clusterCode { get; set; }
        public string departmentCode { get; set; }
        public string divisionCode { get; set; }
        public string sectionCode { get; set; }
        public string unitCode { get; set; }
    
        public virtual tOrgCluster tOrgCluster { get; set; }
        public virtual tOrgDepartment tOrgDepartment { get; set; }
        public virtual tOrgDivision tOrgDivision { get; set; }
        public virtual tOrgSection tOrgSection { get; set; }
        public virtual tOrgUnit tOrgUnit { get; set; }
        public virtual ICollection<tRSPPlantilla> tRSPPlantillas { get; set; }
    }
}
