//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tOrgDepartment
    {
        //public tOrgDepartment()
        //{
        //    this.tOrgStructures = new HashSet<tOrgStructure>();
        //}
    
        public int recNo { get; set; }
        public string departmentCode { get; set; }
        public string departmentName { get; set; }
        public string shortDepartmentName { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string functionCode { get; set; }
    
        public virtual ICollection<tOrgStructure> tOrgStructures { get; set; }
    }
}
