//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPosition
    {
        public tRSPPosition()
        {
            this.tRSPPlantillas = new HashSet<tRSPPlantilla>();
        }
    
        public int recNo { get; set; }
        public string positionCode { get; set; }
        public string positionTitle { get; set; }
        public string shortPositionTitle { get; set; }
        public string acronym { get; set; }
        public Nullable<int> salaryGrade { get; set; }
        public Nullable<int> positionLevel { get; set; }
    
        public virtual ICollection<tRSPPlantilla> tRSPPlantillas { get; set; }
    }
}
