//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPPlantilla
    {
        public tRSPPlantilla()
        {
            this.tRSPlantillaMagnaCartas = new HashSet<tRSPlantillaMagnaCarta>();
            this.tRSPPlantillaPersonnels = new HashSet<tRSPPlantillaPersonnel>();
        }
    
        public int recNo { get; set; }
        public string plantillaCode { get; set; }
        public Nullable<int> oldItemNo { get; set; }
        public Nullable<int> newItemNo { get; set; }
        public string structureCode { get; set; }
        public string positionCode { get; set; }
        public Nullable<bool> isFunded { get; set; }
        public string employmentStatusCode { get; set; }
    
        public virtual tOrgStructure tOrgStructure { get; set; }
        public virtual tRSPEmploymentStatu tRSPEmploymentStatu { get; set; }
        public virtual ICollection<tRSPlantillaMagnaCarta> tRSPlantillaMagnaCartas { get; set; }
        public virtual tRSPPosition tRSPPosition { get; set; }
        public virtual ICollection<tRSPPlantillaPersonnel> tRSPPlantillaPersonnels { get; set; }
    }
}
