//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPMagnaCarta
    {
        public tRSPMagnaCarta()
        {
            this.tRSPlantillaMagnaCartas = new HashSet<tRSPlantillaMagnaCarta>();
        }
    
        public int recNo { get; set; }
        public string magnaCode { get; set; }
        public string magnaCarta { get; set; }
    
        public virtual ICollection<tRSPlantillaMagnaCarta> tRSPlantillaMagnaCartas { get; set; }
    }
}
