//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPSalaryTableDetail
    {
        public int recNo { get; set; }
        public string salaryDetailCode { get; set; }
        public string salaryCode { get; set; }
        public int salaryGrade { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<decimal> rateMonth { get; set; }
        public Nullable<decimal> rateDay { get; set; }
    
        public virtual tRSPSalaryTable tRSPSalaryTable { get; set; }
    }
}
