//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPlantillaMagnaCarta
    {
        public string recNo { get; set; }
        public string plantillaCode { get; set; }
        public string magnaCode { get; set; }
    
        public virtual tRSPMagnaCarta tRSPMagnaCarta { get; set; }
        public virtual tRSPPlantilla tRSPPlantilla { get; set; }
    }
}
