//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRISapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRSPServiceRecord
    {
        public int recNo { get; set; }
        public string EIC { get; set; }
        public Nullable<System.DateTime> dateFrom { get; set; }
        public Nullable<System.DateTime> dateTo { get; set; }
        public string positionTitle { get; set; }
        public string employmentStatus { get; set; }
        public string salary { get; set; }
        public string placeOfAssignment { get; set; }
        public string branch { get; set; }
        public string LWOP { get; set; }
        public string separationCause { get; set; }
    
        public virtual tRSPEmployee tRSPEmployee { get; set; }
    }
}
